In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy import stats
from IPython.display import display,HTML
data=pd.read_csv('tt.csv',header=None,skiprows=1)
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,01-06-2012,16:37,Friday,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,01-06-2012,08:20,Friday,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,01-04-2012,16:17,Wednesday,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
3,01-04-2012,07:53,Wednesday,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,NaN
4,01-03-2012,18:57,Tuesday,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN
5,01-03-2012,07:57,Tuesday,GSK,51.80,135.8,84.5,88.8,NaN,36.8,35.0,No,NaN
6,01-02-2012,17:31,Monday,Home,51.37,123.2,82.9,87.3,NaN,37.2,35.3,No,NaN
7,01-02-2012,07:34,Monday,GSK,49.01,128.3,77.5,85.9,NaN,37.9,34.3,No,NaN
8,12/23/2011,08:01,Friday,GSK,52.91,130.3,80.9,88.3,8.89,39.3,36.0,No,NaN
9,12/22/2011,17:19,Thursday,Home,51.17,122.3,70.6,78.1,8.89,43.5,39.3,No,NaN
10,12/22/2011,08:16,Thursday,GSK,49.15,129.4,74.0,81.4,8.89,39.8,36.2,No,NaN
11,12/21/2011,07:45,Wednesday,GSK,51.77,124.8,71.7,78.9,8.89,43.3,39.4,No,NaN
12,12/20/2011,16:05,Tuesday,Home,51.45,130.1,75.2,82.7,8.89,41.1,37.3,No,NaN
13,12/20/2011,06:04,Tuesday,GSK,49.01,119.0,77.4,82.0,8.89,38.0,35.9,No,NaN
14,12/19/2011,16:18,Monday,Home,51.04,132.2,77.5,83.5,8.89,39.5,36.7,No,NaN
15,12/19/2011,07:34,Monday,GSK,52.00,137.8,76.5,87.8,8.89,40.8,35.5,No,Put snow tires on
16,12/16/2011,12:22,Friday,Home,51.05,128.4,86.9,90.6,9.08,35.2,33.8,No,NaN
17,12/16/2011,07:21,Friday,GSK,49.04,124.6,71.1,80.2,9.08,41.4,36.7,No,NaN
18,12/15/2011,16:14,Thursday,Home,51.06,126.9,80.5,84.9,9.08,38.1,36.1,No,NaN
19,12/15/2011,07:19,Thursday,GSK,51.68,123.5,68.1,75.8,9.08,45.6,40.9,No,NaN
20,12/14/2011,16:20,Wednesday,Home,51.04,123.4,75.1,79.4,9.08,40.8,38.6,No,NaN
21,12/14/2011,07:23,Wednesday,GSK,51.67,123.5,76.6,82.7,9.08,40.5,37.5,No,NaN
22,12/13/2011,17:43,Tuesday,Home,51.15,130.6,74.8,82.4,9.08,41.0,37.2,No,NaN
23,12/13/2011,07:25,Tuesday,GSK,49.19,126.1,65.4,74.2,9.08,45.1,39.8,No,NaN
24,12-12-2011,07:20,Monday,GSK,49.02,126.1,65.7,74.0,9.76,44.8,39.7,No,NaN
25,12-09-2011,12:04,Friday,Home,51.14,126.8,87.3,90.2,9.76,35.2,34.0,No,NaN
26,12-09-2011,07:22,Friday,GSK,51.69,128.4,74.0,77.3,9.76,41.9,40.1,No,NaN
27,12-08-2011,17:41,Thursday,Home,51.07,125.0,74.6,81.5,9.76,41.1,37.6,No,NaN
28,12-08-2011,07:14,Thursday,GSK,51.63,134.4,76.5,84.3,9.76,40.5,36.7,No,NaN
29,12-07-2011,16:12,Wednesday,Home,51.10,126.5,79.9,85.6,9.76,38.4,35.8,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,08-05-2011,17:00,Friday,Home,51.94,126.7,74.5,82.6,8.48,41.9,37.7,No,NaN
176,08-05-2011,08:20,Friday,GSK,49.13,123.9,74.1,79.9,8.48,39.8,36.9,No,NaN
177,08-04-2011,17:38,Thursday,Home,50.96,131.9,70.3,78.5,8.48,43.5,38.9,No,NaN
178,08-04-2011,08:17,Thursday,GSK,49.12,122.4,71.5,77.3,8.48,41.2,38.2,No,NaN
179,08-03-2011,17:14,Wednesday,Home,51.64,125.0,72.2,78.7,8.48,42.9,39.4,No,NaN
180,08-03-2011,08:06,Wednesday,GSK,49.06,121.9,71.5,78.7,8.48,41.2,37.4,No,NaN
181,08-02-2011,17:22,Tuesday,Home,51.16,124.2,76.3,83.2,8.48,40.2,36.9,No,NaN
182,08-02-2011,07:38,Tuesday,GSK,53.48,124.9,68.8,78.8,8.48,46.7,40.7,No,Turn around on Derry
183,7/29/2011,20:31,Friday,Home,50.68,135.6,107.7,110.4,8.45,28.2,27.6,Yes,NaN
184,7/29/2011,08:22,Friday,GSK,49.07,121.1,73.2,77.7,8.45,40.2,37.9,No,Empty roads
185,7/28/2011,17:46,Thursday,Home,51.09,128.5,76.0,84.8,8.45,40.3,36.2,No,NaN
186,7/28/2011,08:11,Thursday,GSK,49.11,120.1,69.1,73.1,8.45,42.6,40.3,No,NaN
187,7/27/2011,17:24,Wednesday,Home,50.98,124.9,68.3,71.9,8.45,44.8,42.6,No,Police slowdown on 403
188,7/27/2011,08:15,Wednesday,GSK,48.82,124.5,70.4,77.8,8.45,41.6,37.6,No,NaN
189,7/26/2011,17:15,Tuesday,Home,51.28,122.1,43.7,51.5,8.45,70.5,59.8,No,Accident blocked 407 exit
190,7/26/2011,08:11,Tuesday,GSK,49.16,122.6,71.9,76.8,8.45,41.0,38.4,No,NaN
191,7/25/2011,16:59,Monday,Home,51.05,126.6,70.4,78.8,8.45,51.1,38.9,No,NaN
192,7/25/2011,08:06,Monday,GSK,48.32,121.2,63.4,78.4,8.45,45.7,37.0,No,NaN
193,7/22/2011,16:47,Friday,Home,51.24,126.3,75.8,81.8,8.28,40.6,37.6,No,NaN
194,7/22/2011,08:28,Friday,GSK,51.05,123.3,88.9,96.7,8.28,34.5,31.7,Yes,NaN
195,7/21/2011,07:59,Thursday,GSK,48.35,129.3,81.5,89.0,8.28,35.6,32.6,Yes,NaN
196,7/20/2011,17:17,Wednesday,Home,53.47,124.0,58.6,71.0,7.89,54.8,45.2,No,NaN
197,7/20/2011,08:24,Wednesday,GSK,48.50,125.8,75.7,87.3,7.89,38.5,33.3,Yes,NaN
198,7/19/2011,17:17,Tuesday,Home,51.16,126.7,92.2,102.6,7.89,33.3,29.9,Yes,NaN
199,7/19/2011,08:11,Tuesday,GSK,50.96,124.3,82.3,96.4,7.89,37.2,31.7,Yes,NaN
200,7/18/2011,08:09,Monday,GSK,54.52,125.6,49.9,82.4,7.89,65.5,39.7,No,NaN
201,7/14/2011,08:03,Thursday,GSK,50.90,123.7,76.2,95.1,7.89,40.1,32.1,Yes,NaN
202,7/13/2011,17:08,Wednesday,Home,51.96,132.6,57.5,76.7,NaN,54.2,40.6,Yes,NaN
203,07-12-2011,17:51,Tuesday,Home,53.28,125.8,61.6,87.6,NaN,51.9,36.5,Yes,NaN
204,07-11-2011,16:56,Monday,Home,51.73,125.0,62.8,92.5,NaN,49.5,33.6,Yes,NaN

In [2]:
import pandas_profiling

report=pandas_profiling.ProfileReport(data)
report

In [3]:
data.describe()

,4,5,6,7,8,9,10
count,205.000000,205.000000,205.000000,205.000000,186.000000,205.000000,205.000000
mean,50.981512,127.591707,74.477561,81.975610,8.690591,41.904390,37.871707
std,1.321205,4.128450,11.409816,10.111544,0.504971,6.849476,4.835072
min,48.320000,112.200000,38.100000,50.300000,7.810000,28.200000,27.100000
25%,50.650000,124.900000,68.900000,76.600000,8.370000,38.400000,35.700000
50%,51.140000,127.400000,73.600000,81.400000,8.520000,41.300000,37.600000
75%,51.630000,129.800000,79.900000,86.000000,8.970000,44.400000,39.900000
max,60.320000,140.900000,107.700000,112.100000,10.050000,82.300000,62.400000

In [4]:
data.dtypes

0      object
1      object
2      object
3      object
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11     object
12     object
dtype: object

In [5]:
df=data.loc[:,4:7]

print(df)

         4      5      6      7
0    51.29  127.4   78.3   84.8
1    51.63  130.3   81.8   88.9
2    51.27  127.4   82.0   85.8
3    49.17  132.3   74.2   82.9
4    51.15  136.2   83.4   88.1
5    51.80  135.8   84.5   88.8
6    51.37  123.2   82.9   87.3
7    49.01  128.3   77.5   85.9
8    52.91  130.3   80.9   88.3
9    51.17  122.3   70.6   78.1
10   49.15  129.4   74.0   81.4
11   51.77  124.8   71.7   78.9
12   51.45  130.1   75.2   82.7
13   49.01  119.0   77.4   82.0
14   51.04  132.2   77.5   83.5
15   52.00  137.8   76.5   87.8
16   51.05  128.4   86.9   90.6
17   49.04  124.6   71.1   80.2
18   51.06  126.9   80.5   84.9
19   51.68  123.5   68.1   75.8
20   51.04  123.4   75.1   79.4
21   51.67  123.5   76.6   82.7
22   51.15  130.6   74.8   82.4
23   49.19  126.1   65.4   74.2
24   49.02  126.1   65.7   74.0
25   51.14  126.8   87.3   90.2
26   51.69  128.4   74.0   77.3
27   51.07  125.0   74.6   81.5
28   51.63  134.4   76.5   84.3
29   51.10  126.5   79.9   85.6
..     ...    ...    ...    ...
175  51.94  126.7   74.5   82.6
176  49.13  123.9   74.1   79.9
177  50.96  131.9   70.3   78.5
178  49.12  122.4   71.5   77.3
179  51.64  125.0   72.2   78.7
180  49.06  121.9   71.5   78.7
181  51.16  124.2   76.3   83.2
182  53.48  124.9   68.8   78.8
183  50.68  135.6  107.7  110.4
184  49.07  121.1   73.2   77.7
185  51.09  128.5   76.0   84.8
186  49.11  120.1   69.1   73.1
187  50.98  124.9   68.3   71.9
188  48.82  124.5   70.4   77.8
189  51.28  122.1   43.7   51.5
190  49.16  122.6   71.9   76.8
191  51.05  126.6   70.4   78.8
192  48.32  121.2   63.4   78.4
193  51.24  126.3   75.8   81.8
194  51.05  123.3   88.9   96.7
195  48.35  129.3   81.5   89.0
196  53.47  124.0   58.6   71.0
197  48.50  125.8   75.7   87.3
198  51.16  126.7   92.2  102.6
199  50.96  124.3   82.3   96.4
200  54.52  125.6   49.9   82.4
201  50.90  123.7   76.2   95.1
202  51.96  132.6   57.5   76.7
203  53.28  125.8   61.6   87.6
204  51.73  125.0   62.8   92.5

[205 rows x 4 columns]

In [6]:
data.corr()

          4         5         6         7         8         9         10
4   1.000000  0.145091 -0.006445  0.011874  0.185989  0.197207  0.197044
5   0.145091  1.000000  0.253869  0.257823 -0.089821 -0.198775 -0.222574
6  -0.006445  0.253869  1.000000  0.872143 -0.148124 -0.877806 -0.835814
7   0.011874  0.257823  0.872143  1.000000 -0.258774 -0.856986 -0.944433
8   0.185989 -0.089821 -0.148124 -0.258774  1.000000  0.201649  0.291869
9   0.197207 -0.198775 -0.877806 -0.856986  0.201649  1.000000  0.920935
10  0.197044 -0.222574 -0.835814 -0.944433  0.291869  0.920935  1.000000

In [7]:
data.cov()

,4,5,6,7,8,9,10
4,1.745583,0.791405,-0.097157,0.158635,0.127033,1.784640,1.258739
5,0.791405,17.044098,11.958440,10.762836,-0.181338,-5.620895,-4.442883
6,-0.097157,11.958440,130.183906,100.619842,-0.871513,-68.601617,-46.109609
7,0.158635,10.762836,100.619842,102.243324,-1.355816,-59.353814,-46.173390
8,0.127033,-0.181338,-0.871513,-1.355816,0.254996,0.706067,0.725966
9,1.784640,-5.620895,-68.601617,-59.353814,0.706067,46.915324,30.499242
10,1.258739,-4.442883,-46.109609,-46.173390,0.725966,30.499242,23.377921

In [8]:
data[2].value_counts()

Tuesday      48
Wednesday    47
Thursday     44
Monday       39
Friday       27
Name: 2, dtype: int64

In [9]:
cleanup_nums = {2:     {"Monday": 1, "Tuesday": 2,"Wednesday":3,"Thursday":4,"Friday":5}}
data.replace(cleanup_nums, inplace=True)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,01-06-2012,16:37,5,Home,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,01-06-2012,08:20,5,GSK,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,01-04-2012,16:17,3,Home,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
3,01-04-2012,07:53,3,GSK,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,NaN
4,01-03-2012,18:57,2,Home,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN

In [10]:
data[3].value_counts()

GSK     105
Home    100
Name: 3, dtype: int64

In [11]:
cleanup_nums = {3:     {"GSK": 1, "Home": 0}}
data.replace(cleanup_nums, inplace=True)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,01-06-2012,16:37,5,0,51.29,127.4,78.3,84.8,NaN,39.3,36.3,No,NaN
1,01-06-2012,08:20,5,1,51.63,130.3,81.8,88.9,NaN,37.9,34.9,No,NaN
2,01-04-2012,16:17,3,0,51.27,127.4,82.0,85.8,NaN,37.5,35.9,No,NaN
3,01-04-2012,07:53,3,1,49.17,132.3,74.2,82.9,NaN,39.8,35.6,No,NaN
4,01-03-2012,18:57,2,0,51.15,136.2,83.4,88.1,NaN,36.8,34.8,No,NaN

In [12]:
data[11].value_counts()

No     170
Yes     35
Name: 11, dtype: int64

In [13]:
cleanup_nums = {11:     {"Yes": 1, "No": 0}}
data.replace(cleanup_nums, inplace=True)
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,01-06-2012,16:37,5,0,51.29,127.4,78.3,84.8,NaN,39.3,36.3,0,NaN
1,01-06-2012,08:20,5,1,51.63,130.3,81.8,88.9,NaN,37.9,34.9,0,NaN
2,01-04-2012,16:17,3,0,51.27,127.4,82.0,85.8,NaN,37.5,35.9,0,NaN
3,01-04-2012,07:53,3,1,49.17,132.3,74.2,82.9,NaN,39.8,35.6,0,NaN
4,01-03-2012,18:57,2,0,51.15,136.2,83.4,88.1,NaN,36.8,34.8,0,NaN

In [14]:
(data.dtypes)

0      object
1      object
2       int64
3       int64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11      int64
12     object
dtype: object

In [15]:
data.corr()

,2,3,4,5,6,7,8,9,10,11
2,1.000000,0.032325,0.007857,0.026630,0.168780,0.167886,0.015742,-0.205607,-0.167358,0.017611
3,0.032325,1.000000,-0.336156,-0.088693,0.023284,0.060624,-0.004218,-0.054361,-0.093739,0.183449
4,0.007857,-0.336156,1.000000,0.145091,-0.006445,0.011874,0.185989,0.197207,0.197044,-0.041145
5,0.026630,-0.088693,0.145091,1.000000,0.253869,0.257823,-0.089821,-0.198775,-0.222574,0.115181
6,0.168780,0.023284,-0.006445,0.253869,1.000000,0.872143,-0.148124,-0.877806,-0.835814,0.532695
7,0.167886,0.060624,0.011874,0.257823,0.872143,1.000000,-0.258774,-0.856986,-0.944433,0.682920
8,0.015742,-0.004218,0.185989,-0.089821,-0.148124,-0.258774,1.000000,0.201649,0.291869,-0.321862
9,-0.205607,-0.054361,0.197207,-0.198775,-0.877806,-0.856986,0.201649,1.000000,0.920935,-0.453187
10,-0.167358,-0.093739,0.197044,-0.222574,-0.835814,-0.944433,0.291869,0.920935,1.000000,-0.573339
11,0.017611,0.183449,-0.041145,0.115181,0.532695,0.682920,-0.321862,-0.453187,-0.573339,1.000000

In [16]:
data.cov()

,2,3,4,5,6,7,8,9,10,11
2,1.726351,0.021282,0.013639,0.144450,2.530253,2.230476,0.010439,-1.850378,-1.063197,0.008728
3,0.021282,0.251076,-0.222543,-0.183477,0.133118,0.307162,-0.001067,-0.186573,-0.227104,0.034672
4,0.013639,-0.222543,1.745583,0.791405,-0.097157,0.158635,0.127033,1.784640,1.258739,-0.020505
5,0.144450,-0.183477,0.791405,17.044098,11.958440,10.762836,-0.181338,-5.620895,-4.442883,0.179364
6,2.530253,0.133118,-0.097157,11.958440,130.183906,100.619842,-0.871513,-68.601617,-46.109609,2.292575
7,2.230476,0.307162,0.158635,10.762836,100.619842,102.243324,-1.355816,-59.353814,-46.173390,2.604675
8,0.010439,-0.001067,0.127033,-0.181338,-0.871513,-1.355816,0.254996,0.706067,0.725966,-0.061508
9,-1.850378,-0.186573,1.784640,-5.620895,-68.601617,-59.353814,0.706067,46.915324,30.499242,-1.170851
10,-1.063197,-0.227104,1.258739,-4.442883,-46.109609,-46.173390,0.725966,30.499242,23.377921,-1.045636
11,0.008728,0.034672,-0.020505,0.179364,2.292575,2.604675,-0.061508,-1.170851,-1.045636,0.142276

In [22]:
data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,01-06-2012,16:37,5,0,51.29,127.4,78.3,84.8,8.52,39.3,36.3,0,NaN
1,01-06-2012,08:20,5,1,51.63,130.3,81.8,88.9,8.52,37.9,34.9,0,NaN
2,01-04-2012,16:17,3,0,51.27,127.4,82.0,85.8,8.52,37.5,35.9,0,NaN
3,01-04-2012,07:53,3,1,49.17,132.3,74.2,82.9,8.52,39.8,35.6,0,NaN
4,01-03-2012,18:57,2,0,51.15,136.2,83.4,88.1,8.52,36.8,34.8,0,NaN
5,01-03-2012,07:57,2,1,51.80,135.8,84.5,88.8,8.52,36.8,35.0,0,NaN
6,01-02-2012,17:31,1,0,51.37,123.2,82.9,87.3,8.52,37.2,35.3,0,NaN
7,01-02-2012,07:34,1,1,49.01,128.3,77.5,85.9,8.52,37.9,34.3,0,NaN
8,12/23/2011,08:01,5,1,52.91,130.3,80.9,88.3,8.89,39.3,36.0,0,NaN
9,12/22/2011,17:19,4,0,51.17,122.3,70.6,78.1,8.89,43.5,39.3,0,NaN
10,12/22/2011,08:16,4,1,49.15,129.4,74.0,81.4,8.89,39.8,36.2,0,NaN
11,12/21/2011,07:45,3,1,51.77,124.8,71.7,78.9,8.89,43.3,39.4,0,NaN
12,12/20/2011,16:05,2,0,51.45,130.1,75.2,82.7,8.89,41.1,37.3,0,NaN
13,12/20/2011,06:04,2,1,49.01,119.0,77.4,82.0,8.89,38.0,35.9,0,NaN
14,12/19/2011,16:18,1,0,51.04,132.2,77.5,83.5,8.89,39.5,36.7,0,NaN
15,12/19/2011,07:34,1,1,52.00,137.8,76.5,87.8,8.89,40.8,35.5,0,Put snow tires on
16,12/16/2011,12:22,5,0,51.05,128.4,86.9,90.6,9.08,35.2,33.8,0,NaN
17,12/16/2011,07:21,5,1,49.04,124.6,71.1,80.2,9.08,41.4,36.7,0,NaN
18,12/15/2011,16:14,4,0,51.06,126.9,80.5,84.9,9.08,38.1,36.1,0,NaN
19,12/15/2011,07:19,4,1,51.68,123.5,68.1,75.8,9.08,45.6,40.9,0,NaN
20,12/14/2011,16:20,3,0,51.04,123.4,75.1,79.4,9.08,40.8,38.6,0,NaN
21,12/14/2011,07:23,3,1,51.67,123.5,76.6,82.7,9.08,40.5,37.5,0,NaN
22,12/13/2011,17:43,2,0,51.15,130.6,74.8,82.4,9.08,41.0,37.2,0,NaN
23,12/13/2011,07:25,2,1,49.19,126.1,65.4,74.2,9.08,45.1,39.8,0,NaN
24,12-12-2011,07:20,1,1,49.02,126.1,65.7,74.0,9.76,44.8,39.7,0,NaN
25,12-09-2011,12:04,5,0,51.14,126.8,87.3,90.2,9.76,35.2,34.0,0,NaN
26,12-09-2011,07:22,5,1,51.69,128.4,74.0,77.3,9.76,41.9,40.1,0,NaN
27,12-08-2011,17:41,4,0,51.07,125.0,74.6,81.5,9.76,41.1,37.6,0,NaN
28,12-08-2011,07:14,4,1,51.63,134.4,76.5,84.3,9.76,40.5,36.7,0,NaN
29,12-07-2011,16:12,3,0,51.10,126.5,79.9,85.6,9.76,38.4,35.8,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,08-05-2011,17:00,5,0,51.94,126.7,74.5,82.6,8.48,41.9,37.7,0,NaN
176,08-05-2011,08:20,5,1,49.13,123.9,74.1,79.9,8.48,39.8,36.9,0,NaN
177,08-04-2011,17:38,4,0,50.96,131.9,70.3,78.5,8.48,43.5,38.9,0,NaN
178,08-04-2011,08:17,4,1,49.12,122.4,71.5,77.3,8.48,41.2,38.2,0,NaN
179,08-03-2011,17:14,3,0,51.64,125.0,72.2,78.7,8.48,42.9,39.4,0,NaN
180,08-03-2011,08:06,3,1,49.06,121.9,71.5,78.7,8.48,41.2,37.4,0,NaN
181,08-02-2011,17:22,2,0,51.16,124.2,76.3,83.2,8.48,40.2,36.9,0,NaN
182,08-02-2011,07:38,2,1,53.48,124.9,68.8,78.8,8.48,46.7,40.7,0,Turn around on Derry
183,7/29/2011,20:31,5,0,50.68,135.6,107.7,110.4,8.45,28.2,27.6,1,NaN
184,7/29/2011,08:22,5,1,49.07,121.1,73.2,77.7,8.45,40.2,37.9,0,Empty roads
185,7/28/2011,17:46,4,0,51.09,128.5,76.0,84.8,8.45,40.3,36.2,0,NaN
186,7/28/2011,08:11,4,1,49.11,120.1,69.1,73.1,8.45,42.6,40.3,0,NaN
187,7/27/2011,17:24,3,0,50.98,124.9,68.3,71.9,8.45,44.8,42.6,0,Police slowdown on 403
188,7/27/2011,08:15,3,1,48.82,124.5,70.4,77.8,8.45,41.6,37.6,0,NaN
189,7/26/2011,17:15,2,0,51.28,122.1,43.7,51.5,8.45,70.5,59.8,0,Accident blocked 407 exit
190,7/26/2011,08:11,2,1,49.16,122.6,71.9,76.8,8.45,41.0,38.4,0,NaN
191,7/25/2011,16:59,1,0,51.05,126.6,70.4,78.8,8.45,51.1,38.9,0,NaN
192,7/25/2011,08:06,1,1,48.32,121.2,63.4,78.4,8.45,45.7,37.0,0,NaN
193,7/22/2011,16:47,5,0,51.24,126.3,75.8,81.8,8.28,40.6,37.6,0,NaN
194,7/22/2011,08:28,5,1,51.05,123.3,88.9,96.7,8.28,34.5,31.7,1,NaN
195,7/21/2011,07:59,4,1,48.35,129.3,81.5,89.0,8.28,35.6,32.6,1,NaN
196,7/20/2011,17:17,3,0,53.47,124.0,58.6,71.0,7.89,54.8,45.2,0,NaN
197,7/20/2011,08:24,3,1,48.50,125.8,75.7,87.3,7.89,38.5,33.3,1,NaN
198,7/19/2011,17:17,2,0,51.16,126.7,92.2,102.6,7.89,33.3,29.9,1,NaN
199,7/19/2011,08:11,2,1,50.96,124.3,82.3,96.4,7.89,37.2,31.7,1,NaN
200,7/18/2011,08:09,1,1,54.52,125.6,49.9,82.4,7.89,65.5,39.7,0,NaN
201,7/14/2011,08:03,4,1,50.90,123.7,76.2,95.1,7.89,40.1,32.1,1,NaN
202,7/13/2011,17:08,3,0,51.96,132.6,57.5,76.7,8.52,54.2,40.6,1,NaN
203,07-12-2011,17:51,2,0,53.28,125.8,61.6,87.6,8.52,51.9,36.5,1,NaN
204,07-11-2011,16:56,1,0,51.73,125.0,62.8,92.5,8.52,49.5,33.6,1,NaN

In [32]:
df=data.loc[:,12:]
df
data.drop[df]

TypeError: 'method' object is not subscriptable

In [24]:
df=data[8]
df

0      8.52
1      8.52
2      8.52
3      8.52
4      8.52
5      8.52
6      8.52
7      8.52
8      8.89
9      8.89
10     8.89
11     8.89
12     8.89
13     8.89
14     8.89
15     8.89
16     9.08
17     9.08
18     9.08
19     9.08
20     9.08
21     9.08
22     9.08
23     9.08
24     9.76
25     9.76
26     9.76
27     9.76
28     9.76
29     9.76
       ...
175    8.48
176    8.48
177    8.48
178    8.48
179    8.48
180    8.48
181    8.48
182    8.48
183    8.45
184    8.45
185    8.45
186    8.45
187    8.45
188    8.45
189    8.45
190    8.45
191    8.45
192    8.45
193    8.28
194    8.28
195    8.28
196    7.89
197    7.89
198    7.89
199    7.89
200    7.89
201    7.89
202    8.52
203    8.52
204    8.52
Name: 8, Length: 205, dtype: float64

In [25]:
df.isnull()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
Name: 8, Length: 205, dtype: bool

In [23]:
median = data[8].median()
data[8].fillna(median, inplace=True)
data.drop[12]
data

TypeError: 'method' object is not subscriptable

In [43]:
df=data.drop([12],axis=1)

In [48]:
df
print(df)
print("THE DATA HAS BEEN STANDERDAIZED BY CONVERTING CATAGERICAL VALUES INTO NUMARIC AND BY FILLING IN THE MISSING VALUES USE MEDIAN METHOD")

             0      1   2   3      4      5      6      7     8     9     10  \
0    01-06-2012  16:37   5   0  51.29  127.4   78.3   84.8  8.52  39.3  36.3
1    01-06-2012  08:20   5   1  51.63  130.3   81.8   88.9  8.52  37.9  34.9
2    01-04-2012  16:17   3   0  51.27  127.4   82.0   85.8  8.52  37.5  35.9
3    01-04-2012  07:53   3   1  49.17  132.3   74.2   82.9  8.52  39.8  35.6
4    01-03-2012  18:57   2   0  51.15  136.2   83.4   88.1  8.52  36.8  34.8
5    01-03-2012  07:57   2   1  51.80  135.8   84.5   88.8  8.52  36.8  35.0
6    01-02-2012  17:31   1   0  51.37  123.2   82.9   87.3  8.52  37.2  35.3
7    01-02-2012  07:34   1   1  49.01  128.3   77.5   85.9  8.52  37.9  34.3
8    12/23/2011  08:01   5   1  52.91  130.3   80.9   88.3  8.89  39.3  36.0
9    12/22/2011  17:19   4   0  51.17  122.3   70.6   78.1  8.89  43.5  39.3
10   12/22/2011  08:16   4   1  49.15  129.4   74.0   81.4  8.89  39.8  36.2
11   12/21/2011  07:45   3   1  51.77  124.8   71.7   78.9  8.89  43.3  39.4
12   12/20/2011  16:05   2   0  51.45  130.1   75.2   82.7  8.89  41.1  37.3
13   12/20/2011  06:04   2   1  49.01  119.0   77.4   82.0  8.89  38.0  35.9
14   12/19/2011  16:18   1   0  51.04  132.2   77.5   83.5  8.89  39.5  36.7
15   12/19/2011  07:34   1   1  52.00  137.8   76.5   87.8  8.89  40.8  35.5
16   12/16/2011  12:22   5   0  51.05  128.4   86.9   90.6  9.08  35.2  33.8
17   12/16/2011  07:21   5   1  49.04  124.6   71.1   80.2  9.08  41.4  36.7
18   12/15/2011  16:14   4   0  51.06  126.9   80.5   84.9  9.08  38.1  36.1
19   12/15/2011  07:19   4   1  51.68  123.5   68.1   75.8  9.08  45.6  40.9
20   12/14/2011  16:20   3   0  51.04  123.4   75.1   79.4  9.08  40.8  38.6
21   12/14/2011  07:23   3   1  51.67  123.5   76.6   82.7  9.08  40.5  37.5
22   12/13/2011  17:43   2   0  51.15  130.6   74.8   82.4  9.08  41.0  37.2
23   12/13/2011  07:25   2   1  49.19  126.1   65.4   74.2  9.08  45.1  39.8
24   12-12-2011  07:20   1   1  49.02  126.1   65.7   74.0  9.76  44.8  39.7
25   12-09-2011  12:04   5   0  51.14  126.8   87.3   90.2  9.76  35.2  34.0
26   12-09-2011  07:22   5   1  51.69  128.4   74.0   77.3  9.76  41.9  40.1
27   12-08-2011  17:41   4   0  51.07  125.0   74.6   81.5  9.76  41.1  37.6
28   12-08-2011  07:14   4   1  51.63  134.4   76.5   84.3  9.76  40.5  36.7
29   12-07-2011  16:12   3   0  51.10  126.5   79.9   85.6  9.76  38.4  35.8
..          ...    ...  ..  ..    ...    ...    ...    ...   ...   ...   ...
175  08-05-2011  17:00   5   0  51.94  126.7   74.5   82.6  8.48  41.9  37.7
176  08-05-2011  08:20   5   1  49.13  123.9   74.1   79.9  8.48  39.8  36.9
177  08-04-2011  17:38   4   0  50.96  131.9   70.3   78.5  8.48  43.5  38.9
178  08-04-2011  08:17   4   1  49.12  122.4   71.5   77.3  8.48  41.2  38.2
179  08-03-2011  17:14   3   0  51.64  125.0   72.2   78.7  8.48  42.9  39.4
180  08-03-2011  08:06   3   1  49.06  121.9   71.5   78.7  8.48  41.2  37.4
181  08-02-2011  17:22   2   0  51.16  124.2   76.3   83.2  8.48  40.2  36.9
182  08-02-2011  07:38   2   1  53.48  124.9   68.8   78.8  8.48  46.7  40.7
183   7/29/2011  20:31   5   0  50.68  135.6  107.7  110.4  8.45  28.2  27.6
184   7/29/2011  08:22   5   1  49.07  121.1   73.2   77.7  8.45  40.2  37.9
185   7/28/2011  17:46   4   0  51.09  128.5   76.0   84.8  8.45  40.3  36.2
186   7/28/2011  08:11   4   1  49.11  120.1   69.1   73.1  8.45  42.6  40.3
187   7/27/2011  17:24   3   0  50.98  124.9   68.3   71.9  8.45  44.8  42.6
188   7/27/2011  08:15   3   1  48.82  124.5   70.4   77.8  8.45  41.6  37.6
189   7/26/2011  17:15   2   0  51.28  122.1   43.7   51.5  8.45  70.5  59.8
190   7/26/2011  08:11   2   1  49.16  122.6   71.9   76.8  8.45  41.0  38.4
191   7/25/2011  16:59   1   0  51.05  126.6   70.4   78.8  8.45  51.1  38.9
192   7/25/2011  08:06   1   1  48.32  121.2   63.4   78.4  8.45  45.7  37.0
193   7/22/2011  16:47   5   0  51.24  126.3   75.8   81.8  8.28  40.6  37.6
194   7/22/2011  08:28   5   1  51.05  123.3   88.9   96.7  8.28  34.5  31.7
195   7/21/2011  07:59   4   1  48.35  129.3   81.5   89.0  8.28  35.6  32.6
196   7/20/2011  17:17   3   0  53.47  124.0   58.6   71.0  7.89  54.8  45.2
197   7/20/2011  08:24   3   1  48.50  125.8   75.7   87.3  7.89  38.5  33.3
198   7/19/2011  17:17   2   0  51.16  126.7   92.2  102.6  7.89  33.3  29.9
199   7/19/2011  08:11   2   1  50.96  124.3   82.3   96.4  7.89  37.2  31.7
200   7/18/2011  08:09   1   1  54.52  125.6   49.9   82.4  7.89  65.5  39.7
201   7/14/2011  08:03   4   1  50.90  123.7   76.2   95.1  7.89  40.1  32.1
202   7/13/2011  17:08   3   0  51.96  132.6   57.5   76.7  8.52  54.2  40.6
203  07-12-2011  17:51   2   0  53.28  125.8   61.6   87.6  8.52  51.9  36.5
204  07-11-2011  16:56   1   0  51.73  125.0   62.8   92.5  8.52  49.5  33.6

     11
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
..   ..
175   0
176   0
177   0
178   0
179   0
180   0
181   0
182   0
183   1
184   0
185   0
186   0
187   0
188   0
189   0
190   0
191   0
192   0
193   0
194   1
195   1
196   0
197   1
198   1
199   1
200   0
201   1
202   1
203   1
204   1

[205 rows x 12 columns]
THE DATA HAS BEEN STANDERDAIZED BY CONVERTING CATAGERICAL VALUES INTO NUMARIC AND BY FILLING IN THE MISSING VALUES USE MEDIAN METHOD

In [51]:
a=df.corr()
print(a)
print("CORRELATION AMONG MOST OF THE ATTRIBUTES ARE LESS AND SOME EVEN HAVE INVERSE CORRELATION which INDICATES THAT MULTIPLE-ATTRIBUTES SHOULD BE TAKEN INTO ACCOUNT HERE TO ARRIVE AT THE CONCLUSION.")

          2         3         4         5         6         7         8   \
2   1.000000  0.032325  0.007857  0.026630  0.168780  0.167886  0.023336
3   0.032325  1.000000 -0.336156 -0.088693  0.023284  0.060624  0.001984
4   0.007857 -0.336156  1.000000  0.145091 -0.006445  0.011874  0.172299
5   0.026630 -0.088693  0.145091  1.000000  0.253869  0.257823 -0.081331
6   0.168780  0.023284 -0.006445  0.253869  1.000000  0.872143 -0.140348
7   0.167886  0.060624  0.011874  0.257823  0.872143  1.000000 -0.253081
8   0.023336  0.001984  0.172299 -0.081331 -0.140348 -0.253081  1.000000
9  -0.205607 -0.054361  0.197207 -0.198775 -0.877806 -0.856986  0.190035
10 -0.167358 -0.093739  0.197044 -0.222574 -0.835814 -0.944433  0.283110
11  0.017611  0.183449 -0.041145  0.115181  0.532695  0.682920 -0.304775

          9         10        11
2  -0.205607 -0.167358  0.017611
3  -0.054361 -0.093739  0.183449
4   0.197207  0.197044 -0.041145
5  -0.198775 -0.222574  0.115181
6  -0.877806 -0.835814  0.532695
7  -0.856986 -0.944433  0.682920
8   0.190035  0.283110 -0.304775
9   1.000000  0.920935 -0.453187
10  0.920935  1.000000 -0.573339
11 -0.453187 -0.573339  1.000000
CORRELATION AMONG MOST OF THE ATTRIBUTES ARE LESS AND SOME EVEN HAVE INVERSE CORRELATION which INDICATES THAT MULTIPLE-ATTRIBUTES SHOULD BE TAKEN INTO ACCOUNT HERE TO ARRIVE AT THE CONCLUSION.

In [46]:
df.cov()

,2,3,4,5,6,7,8,9,10,11
2,1.726351,0.021282,0.013639,0.144450,2.530253,2.230476,0.014823,-1.850378,-1.063197,0.008728
3,0.021282,0.251076,-0.222543,-0.183477,0.133118,0.307162,0.000481,-0.186573,-0.227104,0.034672
4,0.013639,-0.222543,1.745583,0.791405,-0.097157,0.158635,0.110049,1.784640,1.258739,-0.020505
5,0.144450,-0.183477,0.791405,17.044098,11.958440,10.762836,-0.162323,-5.620895,-4.442883,0.179364
6,2.530253,0.133118,-0.097157,11.958440,130.183906,100.619842,-0.774142,-68.601617,-46.109609,2.292575
7,2.230476,0.307162,0.158635,10.762836,100.619842,102.243324,-1.237118,-59.353814,-46.173390,2.604675
8,0.014823,0.000481,0.110049,-0.162323,-0.774142,-1.237118,0.233705,0.629253,0.661749,-0.055575
9,-1.850378,-0.186573,1.784640,-5.620895,-68.601617,-59.353814,0.629253,46.915324,30.499242,-1.170851
10,-1.063197,-0.227104,1.258739,-4.442883,-46.109609,-46.173390,0.661749,30.499242,23.377921,-1.045636
11,0.008728,0.034672,-0.020505,0.179364,2.292575,2.604675,-0.055575,-1.170851,-1.045636,0.142276